# Don't edit this file
#
# It was auto generated by cmake from module.json which should be edited instead

set(DEPENDENT_NAP_MODULES mod_napudp mod_napaudio mod_napimgui)
set(DEEP_DEPENDENT_NAP_MODULES mod_napudp mod_napaudio mod_napimgui mod_napasio mod_napmath mod_napscene mod_naprender mod_napsdlinput mod_napfont mod_napinput mod_napcolor mod_napapp mod_napparameter)
